# Generated by Django 5.2.7 on 2026-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
