# Generated by Django 5.2.7 on 2026-07-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
