# Generated by Django 5.2.7 on 2026-07-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='safety_pledge_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='safety_pledge_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='women_only_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
