# Generated by Django 5.2.7 on 2026-07-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_safety_pledge_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='safety_pledge_accepted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='safety_pledge_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='women_only_confirmed',
        ),
    ]
