# Generated by Django 5.2.7 on 2026-07-13 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('report_created', 'Report created'), ('report_status', 'Report status changed'), ('counselor_status', 'Counselor verification changed')], max_length=40)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('from_value', models.CharField(blank=True, max_length=60)),
                ('to_value', models.CharField(blank=True, max_length=60)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderation.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
