# Generated by Django 5.2.7 on 2025-10-19 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='PsychiatristProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('license_no', models.CharField(max_length=80, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('languages', models.CharField(blank=True, max_length=200)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='psychiatrists/photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_female', models.BooleanField(default=True)),
                ('available_chat', models.BooleanField(default=True)),
                ('available_voice', models.BooleanField(default=True)),
                ('available_video', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychiatrist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('chat', 'Chat'), ('voice', 'Voice'), ('video', 'Video')], default='chat', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('allow_anonymous', models.BooleanField(default=False)),
                ('pseudonym', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='counseling.availabilityslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_bookings', to=settings.AUTH_USER_MODEL)),
                ('psychiatrist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='counseling.psychiatristprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='psychiatrist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='counseling.psychiatristprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together={('psychiatrist', 'start', 'end')},
        ),
    ]
