# Generated by Django 5.2.7 on 2025-10-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychiatristprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Private average rating (optional)', max_digits=3, null=True),
        ),
    ]
